config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :dogs
  resources :icecreams
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/models/icecream.rb
class Icecream < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    def index
      @dogs = Dog.all
    end
  
    def show
      @dog = Dog.find(params[:id])
    end
  
    def new
      @dog = Dog.new
    end
  
  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      redirect_to dogs_path
    else 
      render :new
    end
  end
  
  def edit
    @dog = Dog.find(params[:id])
  end
  
  def update
    @dog = Dog.fnd(params[:id])
    if @dog.update(dog_params)
      redirect_to dogs_path
    else
      render :edit
    end
  end
  
  def destroy
    Dog.find(params[:id])
    redirect_to dogs_path
  end
  
  private
  def dog_params
    params.require(:dog).permit(:breed, :gender, :price)
  end
end

app/controllers/icecreams_controller.rb
class IcecreamsController < ApplicationController
  def index
    @icecreams = Icecream.all
  end

  def show
    @icecream = Icecream.find(params[:id])
  end

  def new
    @icecream = Icecream.new
  end

  def create
    @icecream = Icecream.new(icecream_params)
    if @icecream.save
      redirect_to icereams_path
    else 
      render :new
    end
  end

  def edit
    @icecream = Icecream.find(params[:id])
  end

  def update
    @icecream = Icecream.fnd(params[:id])
    if @iceream.update(icecream_params)
      redirect_to icecreams_path
    else
      render :edit
    end
  end

  def destroy
    Icecream.find(params[:id])
    redirect_to icereams_path
  end

  private
  def icecream_params
    params.require(:icecream).permit(:flavor, :price)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/icecreams_helper.rb
module IcecreamsHelper
end

app/views/dogs/index.html.erb
<h1>The Dog Sanctuary</h1>
<% @dogs.each do |dog| %>
<h2><%= dog.breed%></h2>
<h2><%= dog.gender%></h2>
<h2><%= dog.price%></h2>
<%= link_to  "See our dogs", dog_path(dog)%>
<p>Calling all dog lovers! We are a company that rescues dogs from all over the country, and these fur babies would love to find a new home!.</br>Come check us out at The Dog Sanctuary</p>
<% end %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>
<%= render 'form' %>

app/views/dogs/show.html.erb
<h1><%= @dog.breed %></h1>
<h4><%= @dog.gender %></h1>
<p><%= @dog.price %></p>
<%= link_to 'Back', dogs_path %>

app/views/icecreams/index.html.erb
<h1>Ice Cream Heaven</h1>
<% @icecreams.each do |icecream| %>
<h2><%= icecream.flavor%></h2>
<h2><%= icecream.price%></h2>
<%= link_to  "See our delicious ice cream", icecream_path(icecream)%>
<p>This is icecream heaven, come check out all of our awesome flavors!</p>
<% end %>

app/views/icecreams/new.html.erb
<h1>New Icecream flavors</h1>
<%= render 'form' %>

app/views/icecreams/show.html.erb
<h1><%= @icecream.flavor %></h1>
<h4><%= @icecream.price %></h1>
<%= link_to 'Back', icecreams_path %>

app/views/layouts/_navbar.html.erb
  <nav>
    <div class="nav-wrapper pink">
    <h1 class="brand-logo"><%= link_to  "Dogs & Ice Cream", root_path %></h1>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to  "Home", root_path %></li>
        <li><%= link_to  "Adopt a Dog", dogs_path %></li>
        <li><%= link_to 'Ice Cream Stop', icecreams_path%></li>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frankenstein</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="home">
<h1 class="homewelcome">Welcome to Dogs & Ice Cream!!</h1>
<p class="homep">A place where you can adopt cute doggies and get ice cream on the way out!</p>
<button class="waves-effect grey darken-3 btn"><%= link_to  "Browse Here", dogs_path%></button>
</div>